# Generated by Django 2.1.5 on 2020-01-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boookshelf',
            name='learge_category',
        ),
        migrations.DeleteModel(
            name='BoookShelf',
        ),
    ]
