# Generated by Django 2.1.5 on 2020-01-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookshelf', '0002_auto_20200118_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_shelf_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='本棚名')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bookshelf.Book', verbose_name='書籍(FK)')),
            ],
            options={
                'verbose_name_plural': '本棚マスタ',
                'db_table': 'book_shelf_master',
            },
        ),
    ]
